vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profile_file:
            uri_prefix: /uploads/pictures/profile
            upload_destination: "%upload_directory%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer